Repository terraform-providers/terraform-provider-powerdns, pull requests merged in 2019-08, with the labels that each got.

#23 Improve docker-compose file
  docker-compose.yml
Labels: size/XS

#26 Added acceptance tests commands to travis-ci
  .travis.yml
Labels: size/XS

#24 Don't detectVersion on client creation
  powerdns/client.go
Labels: size/S

#28 Add support for multiple server URL formats
  go.mod
  powerdns/client.go
  powerdns/client_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/XXL

#22 add option to skip TLS verification of server's cert
  .travis.yml
  README.md
  docker-compose.yml
  go.mod
  go.sum
  powerdns/client.go
  powerdns/client_test.go
  powerdns/config.go
  powerdns/provider.go
  powerdns/provider_test.go
  tests/files/README.md
  tests/files/nginx/nginx.conf
  tests/files/ssl/localhost-csr.conf
  tests/files/ssl/localhost/.gitignore
  tests/files/ssl/localhost/server.crt
  tests/files/ssl/localhost/server.key
  tests/files/ssl/root-csr.conf
  tests/files/ssl/rootCA.conf
  tests/files/ssl/rootCA/.gitignore
  tests/files/ssl/rootCA/private/rootCA.key
  tests/files/ssl/rootCA/rootCA.crt
  vendor/github.com/hashicorp/terraform/helper/pathorcontents/read.go
  vendor/modules.txt
  website/docs/index.html.markdown
Labels: dependencies, documentation, size/XL

#27 Add linting
  .travis.yml
  GNUmakefile
  README.md
  powerdns/client.go
  powerdns/client_test.go
  powerdns/config.go
  powerdns/provider.go
  powerdns/resource_powerdns_record.go
  powerdns/resource_powerdns_record_test.go
  powerdns/resource_powerdns_zone.go
Labels: size/L
