Repository terraform-providers/terraform-provider-powerdns, pull requests merged in 2019-11, with the labels that each got.

#39 Update starting dev docs
  .gitignore
  README.md
Labels: size/XS

#40 add option soa_edit_api
  GNUmakefile
  docker-compose.yml
  powerdns/client.go
  powerdns/resource_powerdns_record_test.go
  powerdns/resource_powerdns_zone.go
  powerdns/resource_powerdns_zone_test.go
  website/docs/r/zone.html.markdown
Labels: documentation, size/M

#42 add tests for ALIAS type
  powerdns/resource_powerdns_record_test.go
Labels: size/S
