Repository terraform-providers/terraform-provider-powerdns, pull requests merged in 2019-09, with the labels that each got.

#30 Add tests for SOA records
  docker-compose.yml
  powerdns/resource_powerdns_record_test.go
Labels: size/XS

#35 validate value of records
  powerdns/resource_powerdns_record.go
  powerdns/resource_powerdns_record_test.go
Labels: size/S

#32 zone and record resources import
  powerdns/resource_powerdns_record.go
  powerdns/resource_powerdns_record_test.go
  powerdns/resource_powerdns_zone.go
  powerdns/resource_powerdns_zone_test.go
  website/docs/r/record.html.markdown
  website/docs/r/zone.html.markdown
Labels: documentation, size/XL
