Repository terraform-providers/terraform-provider-powerdns, pull requests merged in 2020-01, with the labels that each got.

#51 Update client tests
  .travis.yml
  CHANGELOG.md
  powerdns/client_test.go
Labels: size/M

#50 Made changes to documentation regarding deprecation and usage of set_ptr
  website/docs/r/record.html.markdown
Labels: documentation, size/XS

#52 Add ServerVersion attribute to client
  CHANGELOG.md
  powerdns/client.go
Labels: size/S
